export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_WITH_GOOGLE = 'SIGN_IN_WITH_GOOGLE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SET_IS_ERROR = 'SET_IS_ERROR';
export const SET_IS_ERROR_TRIGGER = 'SET_IS_ERROR_TRIGGER';
