export const ADD_POST = 'ADD_POST';
export const ADD_POST_TRIGGER = 'ADD_POST_TRIGGER';
export const VIEW_USER_POSTS = 'VIEW_USER_POSTS';
export const VIEW_USER_POSTS_TRIGGER = 'VIEW_USER_POSTS_TRIGGER';
export const VIEW_ALL_POSTS = 'VIEW_ALL_POSTS';
export const VIEW_ALL_POSTS_TRIGGER = 'VIEW_ALL_POSTS_TRIGGER';
