export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_WITH_GOOGLE = 'SIGN_UP_WITH_GOOGLE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SET_IS_ERROR = 'SET_IS_ERROR';
export const SET_IS_ERROR_TRIGGER = 'SET_IS_ERROR_TRIGGER';
